services:
  strapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: strapi-backend
    ports:
      - "${STRAPI_PORT}:${STRAPI_PORT}"
    volumes:
      - ./backend/data:/app/data
    environment:
      - NODE_ENV=development
      - HOST=${STRAPI_HOST}
      - PORT=${STRAPI_PORT}
      - APP_KEYS=${APP_KEYS}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_FILENAME=${DATABASE_FILENAME}
      - JWT_SECRET=${JWT_SECRET}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_STRAPI_URL=${VITE_STRAPI_URL}
    image: vue-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - VITE_STRAPI_URL=${VITE_STRAPI_URL}
    depends_on:
      - strapi
